language: node_js
node_js: stable

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_deployment_dey # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
